#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --debian-installer live \
    --debian-installer-distribution trixie \
    --distribution trixie \
    --architectures amd64 \
    "${@}"
