#!/bin/sh

set -e

lb config noauto \
    --mode debian \
    --debian-installer live \
    --debian-installer-distribution trixie \
    --distribution trixie \
    --archive-areas "main contrib non-free non-free-firmware" \
    --architectures amd64 \
    --security false \
    --apt-indices false \
    "${@}"
